// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/msrshahrukh100/Golang-Clean-Architecture-webapi/controller"
	"github.com/msrshahrukh100/Golang-Clean-Architecture-webapi/repository"
	"github.com/msrshahrukh100/Golang-Clean-Architecture-webapi/service"
)

// Injectors from wire.go:

func InitializeEvent() *controller.PostController {
	repositoryRepository := repository.NewFirestoreRepository()
	serviceService := service.NewPostService(repositoryRepository)
	controllerPostController := controller.NewPostController(serviceService)
	return controllerPostController
}
